<?php $smiles_search=array (
  0 => ':)',
  1 => ':-)',
  2 => '(-:',
  3 => '(:)',
  4 => ':(',
  5 => ':-(',
  6 => ';)',
  7 => ';-)',
  8 => ':-/',
  9 => ':-',
  10 => ':S',
  11 => ':x',
  12 => ':-x',
  13 => '(L)',
  14 => '',
  15 => ':&quot;>',
  16 => ':$',
  17 => ':-P',
  18 => ':P',
  19 => ':-*',
  20 => ':*',
  21 => '(K)',
  22 => '=((',
  23 => '(U)',
  24 => ':-O',
  25 => ':O',
  26 => 'X-(',
  27 => 'X(',
  28 => ':@',
  29 => 'B-)',
  30 => '(H)',
  31 => '>:)',
  32 => '(6)',
  33 => ':((',
  34 => ':-((',
  35 => ':\'(',
  36 => ':|',
  37 => ':-|',
  38 => '/:)',
  39 => '/:-)',
  40 => '^o)',
  41 => 'o:-)',
  42 => '0:-)',
  43 => 'o:)',
  44 => '0:)',
  45 => '(A)',
  46 => ':-B',
  47 => ':B',
  48 => '8-|',
  49 => '8-)',
  50 => ':-&',
  51 => '+o(',
  52 => ':-$',
  53 => ':-#',
  54 => '&lt;:-P',
  55 => '&lt;:o)',
  56 => '(:|',
  57 => '(:}',
  58 => ':-?',
  59 => '*-)',
  60 => ':))',
  61 => ':-))',
  62 => '=))',
  63 => ':D',
  64 => ';-D',
  65 => ';;)',
  66 => ';;-)',
  67 => '&lt;:D>',
  68 => ':->',
  69 => ':>',
  70 => ':-S',
  71 => '#:-S',
  72 => '=;',
  73 => 'I-)',
  74 => '|-)',
  75 => 'L-)',
  76 => '[-(',
  77 => ':o)',
  78 => ':0',
  79 => '&lt;@:)',
  80 => '8-}',
  81 => '=P~',
  82 => '#-o',
  83 => '=D>',
  84 => ':-SS',
  85 => '@-)',
  86 => ':^O',
  87 => ':-w',
  88 => ';-&lt;',
  89 => '>:P',
  90 => '&lt;):)',
  91 => ':)]',
  92 => ':-c',
  93 => '~x(',
  94 => ':-h',
  95 => ':-t',
  96 => '8->',
  97 => ':-??',
  98 => '%-(',
  99 => ':o3',
  100 => 'X_X',
  101 => ':!!',
  102 => '\\m/',
  103 => ':@)',
  104 => '3:-O',
  105 => '3:-0',
  106 => ':(|)',
  107 => '~:>',
  108 => '@};-',
  109 => '%%-',
  110 => '**==',
  111 => '(~~)',
  112 => '~o)',
  113 => '*-:)',
  114 => '8-X',
  115 => '=:)',
  116 => '=:-)',
  117 => '>-)',
  118 => ':-L',
  119 => '[-O&lt;',
  120 => '$-)',
  121 => ':-&quot;',
  122 => 'b-(',
  123 => ':)>-',
  124 => '[-X',
  125 => ':D/',
  126 => '>:/',
  127 => ';))',
  128 => 'o->',
  129 => 'o=>',
  130 => 'o-+',
  131 => '(%)',
  132 => ':-@',
  133 => '^:)^',
  134 => ':-j',
  135 => '(*)',
  136 => ':-q',
  137 => ':-bd',
  138 => '^#(^',
  139 => ':bz',
);$smiles_replace=array (
  0 => '<img src=\'skins/default/images/Smileys/1.gif\'>',
  1 => '<img src=\'skins/default/images/Smileys/1.gif\'>',
  2 => '<img src=\'skins/default/images/Smileys/1.gif\'>',
  3 => '<img src=\'skins/default/images/Smileys/1.gif\'>',
  4 => '<img src=\'skins/default/images/Smileys/2.gif\'>',
  5 => '<img src=\'skins/default/images/Smileys/2.gif\'>',
  6 => '<img src=\'skins/default/images/Smileys/3.gif\'>',
  7 => '<img src=\'skins/default/images/Smileys/3.gif\'>',
  8 => '<img src=\'skins/default/images/Smileys/7.gif\'>',
  9 => '<img src=\'skins/default/images/Smileys/7.gif\'>',
  10 => '<img src=\'skins/default/images/Smileys/7.gif\'>',
  11 => '<img src=\'skins/default/images/Smileys/8.gif\'>',
  12 => '<img src=\'skins/default/images/Smileys/8.gif\'>',
  13 => '<img src=\'skins/default/images/Smileys/8.gif\'>',
  14 => '<img src=\'skins/default/images/Smileys/8.gif\'>',
  15 => '<img src=\'skins/default/images/Smileys/9.gif\'>',
  16 => '<img src=\'skins/default/images/Smileys/9.gif\'>',
  17 => '<img src=\'skins/default/images/Smileys/10.gif\'>',
  18 => '<img src=\'skins/default/images/Smileys/10.gif\'>',
  19 => '<img src=\'skins/default/images/Smileys/11.gif\'>',
  20 => '<img src=\'skins/default/images/Smileys/11.gif\'>',
  21 => '<img src=\'skins/default/images/Smileys/11.gif\'>',
  22 => '<img src=\'skins/default/images/Smileys/12.gif\'>',
  23 => '<img src=\'skins/default/images/Smileys/12.gif\'>',
  24 => '<img src=\'skins/default/images/Smileys/13.gif\'>',
  25 => '<img src=\'skins/default/images/Smileys/13.gif\'>',
  26 => '<img src=\'skins/default/images/Smileys/14.gif\'>',
  27 => '<img src=\'skins/default/images/Smileys/14.gif\'>',
  28 => '<img src=\'skins/default/images/Smileys/14.gif\'>',
  29 => '<img src=\'skins/default/images/Smileys/16.gif\'>',
  30 => '<img src=\'skins/default/images/Smileys/16.gif\'>',
  31 => '<img src=\'skins/default/images/Smileys/19.gif\'>',
  32 => '<img src=\'skins/default/images/Smileys/19.gif\'>',
  33 => '<img src=\'skins/default/images/Smileys/20.gif\'>',
  34 => '<img src=\'skins/default/images/Smileys/20.gif\'>',
  35 => '<img src=\'skins/default/images/Smileys/20.gif\'>',
  36 => '<img src=\'skins/default/images/Smileys/22.gif\'>',
  37 => '<img src=\'skins/default/images/Smileys/22.gif\'>',
  38 => '<img src=\'skins/default/images/Smileys/23.gif\'>',
  39 => '<img src=\'skins/default/images/Smileys/23.gif\'>',
  40 => '<img src=\'skins/default/images/Smileys/23.gif\'>',
  41 => '<img src=\'skins/default/images/Smileys/25.gif\'>',
  42 => '<img src=\'skins/default/images/Smileys/25.gif\'>',
  43 => '<img src=\'skins/default/images/Smileys/25.gif\'>',
  44 => '<img src=\'skins/default/images/Smileys/25.gif\'>',
  45 => '<img src=\'skins/default/images/Smileys/25.gif\'>',
  46 => '<img src=\'skins/default/images/Smileys/26.gif\'>',
  47 => '<img src=\'skins/default/images/Smileys/26.gif\'>',
  48 => '<img src=\'skins/default/images/Smileys/29.gif\'>',
  49 => '<img src=\'skins/default/images/Smileys/29.gif\'>',
  50 => '<img src=\'skins/default/images/Smileys/31.gif\'>',
  51 => '<img src=\'skins/default/images/Smileys/31.gif\'>',
  52 => '<img src=\'skins/default/images/Smileys/32.gif\'>',
  53 => '<img src=\'skins/default/images/Smileys/32.gif\'>',
  54 => '<img src=\'skins/default/images/Smileys/36.gif\'>',
  55 => '<img src=\'skins/default/images/Smileys/36.gif\'>',
  56 => '<img src=\'skins/default/images/Smileys/37.gif\'>',
  57 => '<img src=\'skins/default/images/Smileys/37.gif\'>',
  58 => '<img src=\'skins/default/images/Smileys/39.gif\'>',
  59 => '<img src=\'skins/default/images/Smileys/39.gif\'>',
  60 => '<img src=\'skins/default/images/Smileys/21.gif\'>',
  61 => '<img src=\'skins/default/images/Smileys/21.gif\'>',
  62 => '<img src=\'skins/default/images/Smileys/24.gif\'>',
  63 => '<img src=\'skins/default/images/Smileys/4.gif\'>',
  64 => '<img src=\'skins/default/images/Smileys/4.gif\'>',
  65 => '<img src=\'skins/default/images/Smileys/5.gif\'>',
  66 => '<img src=\'skins/default/images/Smileys/5.gif\'>',
  67 => '<img src=\'skins/default/images/Smileys/6.gif\'>',
  68 => '<img src=\'skins/default/images/Smileys/15.gif\'>',
  69 => '<img src=\'skins/default/images/Smileys/15.gif\'>',
  70 => '<img src=\'skins/default/images/Smileys/17.gif\'>',
  71 => '<img src=\'skins/default/images/Smileys/18.gif\'>',
  72 => '<img src=\'skins/default/images/Smileys/27.gif\'>',
  73 => '<img src=\'skins/default/images/Smileys/28.gif\'>',
  74 => '<img src=\'skins/default/images/Smileys/28.gif\'>',
  75 => '<img src=\'skins/default/images/Smileys/30.gif\'>',
  76 => '<img src=\'skins/default/images/Smileys/33.gif\'>',
  77 => '<img src=\'skins/default/images/Smileys/34.gif\'>',
  78 => '<img src=\'skins/default/images/Smileys/34.gif\'>',
  79 => '<img src=\'skins/default/images/Smileys/34.gif\'>',
  80 => '<img src=\'skins/default/images/Smileys/35.gif\'>',
  81 => '<img src=\'skins/default/images/Smileys/38.gif\'>',
  82 => '<img src=\'skins/default/images/Smileys/40.gif\'>',
  83 => '<img src=\'skins/default/images/Smileys/41.gif\'>',
  84 => '<img src=\'skins/default/images/Smileys/42.gif\'>',
  85 => '<img src=\'skins/default/images/Smileys/43.gif\'>',
  86 => '<img src=\'skins/default/images/Smileys/44.gif\'>',
  87 => '<img src=\'skins/default/images/Smileys/45.gif\'>',
  88 => '<img src=\'skins/default/images/Smileys/46.gif\'>',
  89 => '<img src=\'skins/default/images/Smileys/47.gif\'>',
  90 => '<img src=\'skins/default/images/Smileys/48.gif\'>',
  91 => '<img src=\'skins/default/images/Smileys/100.gif\'>',
  92 => '<img src=\'skins/default/images/Smileys/101.gif\'>',
  93 => '<img src=\'skins/default/images/Smileys/102.gif\'>',
  94 => '<img src=\'skins/default/images/Smileys/103.gif\'>',
  95 => '<img src=\'skins/default/images/Smileys/104.gif\'>',
  96 => '<img src=\'skins/default/images/Smileys/105.gif\'>',
  97 => '<img src=\'skins/default/images/Smileys/106.gif\'>',
  98 => '<img src=\'skins/default/images/Smileys/107.gif\'>',
  99 => '<img src=\'skins/default/images/Smileys/108.gif\'>',
  100 => '<img src=\'skins/default/images/Smileys/109.gif\'>',
  101 => '<img src=\'skins/default/images/Smileys/110.gif\'>',
  102 => '<img src=\'skins/default/images/Smileys/111.gif\'>',
  103 => '<img src=\'skins/default/images/Smileys/49.gif\'>',
  104 => '<img src=\'skins/default/images/Smileys/50.gif\'>',
  105 => '<img src=\'skins/default/images/Smileys/50.gif\'>',
  106 => '<img src=\'skins/default/images/Smileys/51.gif\'>',
  107 => '<img src=\'skins/default/images/Smileys/52.gif\'>',
  108 => '<img src=\'skins/default/images/Smileys/53.gif\'>',
  109 => '<img src=\'skins/default/images/Smileys/54.gif\'>',
  110 => '<img src=\'skins/default/images/Smileys/55.gif\'>',
  111 => '<img src=\'skins/default/images/Smileys/56.gif\'>',
  112 => '<img src=\'skins/default/images/Smileys/57.gif\'>',
  113 => '<img src=\'skins/default/images/Smileys/58.gif\'>',
  114 => '<img src=\'skins/default/images/Smileys/59.gif\'>',
  115 => '<img src=\'skins/default/images/Smileys/60.gif\'>',
  116 => '<img src=\'skins/default/images/Smileys/60.gif\'>',
  117 => '<img src=\'skins/default/images/Smileys/61.gif\'>',
  118 => '<img src=\'skins/default/images/Smileys/62.gif\'>',
  119 => '<img src=\'skins/default/images/Smileys/63.gif\'>',
  120 => '<img src=\'skins/default/images/Smileys/64.gif\'>',
  121 => '<img src=\'skins/default/images/Smileys/65.gif\'>',
  122 => '<img src=\'skins/default/images/Smileys/66.gif\'>',
  123 => '<img src=\'skins/default/images/Smileys/67.gif\'>',
  124 => '<img src=\'skins/default/images/Smileys/68.gif\'>',
  125 => '<img src=\'skins/default/images/Smileys/69.gif\'>',
  126 => '<img src=\'skins/default/images/Smileys/70.gif\'>',
  127 => '<img src=\'skins/default/images/Smileys/71.gif\'>',
  128 => '<img src=\'skins/default/images/Smileys/72.gif\'>',
  129 => '<img src=\'skins/default/images/Smileys/73.gif\'>',
  130 => '<img src=\'skins/default/images/Smileys/74.gif\'>',
  131 => '<img src=\'skins/default/images/Smileys/75.gif\'>',
  132 => '<img src=\'skins/default/images/Smileys/76.gif\'>',
  133 => '<img src=\'skins/default/images/Smileys/77.gif\'>',
  134 => '<img src=\'skins/default/images/Smileys/78.gif\'>',
  135 => '<img src=\'skins/default/images/Smileys/79.gif\'>',
  136 => '<img src=\'skins/default/images/Smileys/112.gif\'>',
  137 => '<img src=\'skins/default/images/Smileys/113.gif\'>',
  138 => '<img src=\'skins/default/images/Smileys/114.gif\'>',
  139 => '<img src=\'skins/default/images/Smileys/115.gif\'>',
);?>